name: Package Elastic Beanstalk

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create deployment zip
        run: zip -r deploy-web-linux.zip Dockerfile Area42-1.Web Area42-1.ServiceDefaults

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-web-linux
          path: deploy-web-linux.zip
